version: '3'
services:
  check_mk_exporter:
    build: .
    ports:
      - "2112:2112"
    volumes:
      - "./docker/etc/check_mk_exporter/:/etc/check_mk_exporter/"
      - "./docker/ssh/client/:/app/.ssh/"
    command:
      - "/bin/check_mk_exporter"
      - "--log.level=trace"
  target_1:
    image: fedora/ssh
    volumes:
      - "./testdata/:/testdata/"
      - "./docker/bin/:/usr/local/bin/"
      - "./docker/ssh/server/:/home/user/.ssh"
    command:
      - "/usr/sbin/sshd"
      - "-D"
      - "-d"
    restart: always
